config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'

  get 'pokemon', to: 'pokemon#index'

  post 'pokemon', to: 'pokemon#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home', as: :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController

  POKEMON = {
    1 => { name: "Gloom", location: "Route 28", category: "Grass" },
    2 => { name: "Pikachu", location: "Route 3", category: "Electric" }
  }

  def index
    @category = params[:pokemon_type]
    if params[:pokemon_type].blank?
      @pokemon = POKEMON
    else
      @pokemon = POKEMON.select { |id, r| r[:category] == @category }
    end
  end

  def create
    raise
    puts "TODO: create the pokemon in the DB"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Icarus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Pokemon</h1>

    <%= yield %>

    <p>footer</p>
    <%= link_to 'about', about_path %>
    <%= link_to 'contact', contact_path %>
    <%= link_to 'home', home_path %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>home page</h1>

<form action="/pokemon" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="location" placeholder="location">
  <input type="text" name="category" placeholder="category">
  <input type="submit">
</form>

<%= link_to 'search pokemon', pokemon_path %>

app/views/pokemon/index.html.erb
<h5>List</h5>

<form action="/pokemon" method="get">
  <input type="text" name="pokemon_type" placeholder="What type of pokemon?">
  <input type="submit">
</form>

<ul>
  <% @pokemon.each do |id, pokemon| %>
    <li><%= pokemon[:name] %></li>
  <% end %>
</ul>